from sqlalchemy import Boolean, Column, Integer, String, DateTime, Date, ForeignKey
from app.core.database import Base

class Os(Base):
    __tablename__ = "os"

    os_id = Column(String(8), primary_key=True, index=True)
    os_num = Column(Integer, nullable=True)
    fecha = Column(Date, nullable=False)
    centro_id = Column(String(8), ForeignKey("centro.centro_id"), nullable=False)
    cliente_id = Column(String(8), ForeignKey("cliente.cliente_id"), nullable=False)
    producto_id = Column(String(8), ForeignKey("producto.producto_id"), nullable=False)
    tipo_servicio_id = Column(String(8), ForeignKey("tipo_servicio.tipo_servicio_id"), nullable=False)
    servicio_id = Column(String(8), ForeignKey("servicio.servicio_id"), nullable=False)
    ruta_id = Column(String(8), ForeignKey("ruta.ruta_id"), nullable=False)
    tipo_informe = Column(String(45), nullable=True)
    patente = Column(String(7), nullable=True)
    contenedor = Column(String(30), nullable=True)
    transporte = Column(String(32), nullable=False)
    tipo_plan = Column(String(16), nullable=False)
    turno = Column(String(16), nullable=False)
    reserva = Column(String(50), nullable=True)
    creado_por = Column(String(64), nullable=True)
    creacion_fecha = Column(DateTime, nullable=True)
    status = Column(String(16), nullable=True)
    status_por = Column(String(64), nullable=True)
    status_fecha = Column(DateTime, nullable=True)
    status_comentario = Column(String(128), nullable=True)
    status_responsable = Column(String(32), nullable=True)
    os_reprogramada = Column(Integer, nullable=True)
    os_estado = Column(String(10), nullable=True)
    estado_por = Column(String(100), nullable=True)
    estado_fecha = Column(DateTime, nullable=True)
    os_entrada = Column(DateTime, nullable=True)
    os_salida = Column(DateTime, nullable=True)
    os_comentario = Column(String(100), nullable=True)
    secuencia = Column(Integer, nullable=True)
    os_contenedor = Column(String(45), nullable=True)
    interpolar_id = Column(String(45), nullable=True)
    rut_conductor = Column(String(45), nullable=True)
    nombre_conductor = Column(String(64), nullable=True)
    horario = Column(Integer, nullable=True)
    contenedor_2 = Column(String(11), nullable=True)
    orden = Column(String(45), nullable=True)
    salida_puerto = Column(Date, nullable=True)
    salida_puerto2 = Column(Date, nullable=True)
    um_id = Column(String(8), nullable=True)
    os_hab = Column(String(45), nullable=True)
    solicitante_id = Column(String(50), ForeignKey("solicitante.solicitante_id"), nullable=True)
    deposito = Column(String(45), nullable=True)
    cierre_stacking = Column(Date, nullable=True)
    nave = Column(String(45), nullable=True)
    sag = Column(Boolean, nullable=True)  # Usamos Boolean para un bit(1)
    comentario = Column(String(45), nullable=True)
    fecha_guia = Column(DateTime, nullable=True)
